# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYB_iOSComponent' do
    
    pod 'Masonry'
    
    target 'YYB_iOSComponentTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'YYB_iOSComponentUITests' do
        inherit! :search_paths
        # Pods for testing
    end

end
